### PR TITLE
Add catch2 support

### PR DESCRIPTION
**Pull request by salim-runsafe**
This should address #53

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @salim-runsafe,

Thanks a lot, this is a great contribution!

However it seems some of the tests are failing, can you please take a look? Thanks!

**Comment by salim-runsafe** [comment]
> Hi @salim-runsafe,
> 
> Thanks a lot, this is a great contribution!
> 
> However it seems some of the tests are failing, can you please take a look? Thanks!

@nicoddemus I get the same errors when I run with the base repo's `master`. I think some dependencies might have shifted since the last release?

**Comment by salim-runsafe** [comment]
@nicoddemus For the `test_cpp_files_option` errors, pytest 6 changed its output message so `--collect-only` will say `"* no tests collected *"` rather than `"* no tests ran *"`. How do you feel about changing that check to `* no tests *`? I don't mind doing it in this PR.

**Comment by salim-runsafe** [comment]
For the other failures, there is a comment in `boost.py`,

```
        # Fatal errors apparently generate invalid xml in the form:
        # <FatalError>...</FatalError><TestLog>...</TestLog>
        # so we have to manually split it into two xmls if that's the case.
```

The XML that it is failing to parse looks to follow that pattern, but with `<Exception>` rather than `<FatalError>`;

```
<Exception file="unknown location" line="0"><![CDATA[std::runtime_error: This is a global fixture init failure]]></Exception><TestLog></TestLog>
```

**Comment by nicoddemus** [comment]
> @nicoddemus I get the same errors when I run with the base repo's master. I think some dependencies might have shifted since the last release?

Ahh that's definitely possible, `pytest-cpp` doesn't build that frequently.

> How do you feel about changing that check to * no tests *? I don't mind doing it in this PR.

Sounds good, thanks!

> The XML that it is failing to parse looks to follow that pattern, but with <Exception> rather than <FatalError>

Ahh thanks for checking. Perhaps we can update the code to support both cases?

While of course those failures are out of the scope of your PR, fixing them would be much welcome, if you have the time and disposition. 🙇

**Comment by nicoddemus** [comment]
@salim-runsafe thanks a lot for fixing the issues!

Python 2.7 and 3.5 are failing because of issues with `setuptools-scm`:

```
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
```

There's a workaround for that (@RonnyPfannschmidt do you remember the workaround?), but unless you need support for those platforms, I'm also OK with dropping support for Python 2.7 and 3.5, which are EOL now. What do you think?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus the easiest way is to preinstall it and/or ensure modern pip/setuptools are used, a release of setuptools_scm with better errors is intended to be released "soon (tm)"

**Comment by nicoddemus** [comment]
Ahh right, thanks @RonnyPfannschmidt!

**Comment by salim-runsafe** [comment]
@nicoddemus I'm all for removing 2.7 and 3.5 since they're EOL and will push a commit with that, but if you'd rather preinstall `setuptools_scm` I can revert it and do that instead.

**Comment by nicoddemus** [comment]
Awesome, thanks a lot! I will merge as soon as CI passes, and then release `2.0.0`. 🎉

**Comment by nicoddemus** [comment]
2.0.0 is out! Thanks again @salim-runsafe, awesome contribution!

**Pull request merged**
