### PR TITLE
Add cpp_harness option to invoke test with a tool

### LINKED ISSUE #49: Add a way to use valgrind, catchsegv or similar tool
Tools like valgrind and catchsegv are used in this way

```
valgrind --tool=memcheck gtest-binary
```

I think a way of using something like that would be to add a `pytest_addoption` on the `ini` like

```
[pytest]
harness = valgrind --tool=memcheck 
```

thoughts? recommendations?

### PR DESCRIPTION
**Pull request by dajose**
Closes #49

Probably the PR checks will fail as I am using valgrind but I did not added it to the travis worker. I did that on purpose as I am not sure what kind of test you'd like for this

### CODE REVIEW

**Comment by dajose** [comment]
glad you folks liked it :)

**Comment by dajose** [comment]
I pushed some fixes and realize that I broke python2 support. Sincere question: fix or drop python2?

**Comment by dajose** [comment]
please dont merge yet, I think I found a bug

**Comment by dajose** [comment]
never mind, I was doing something dumb on my local test :sweat_smile:

**Comment by dajose** [comment]
@tadeu is it ok to merge? or should we wait for @nicoddemus review?

**Comment by dajose** [comment]
@tadeu is it ok to merge this? or should we wait for @nicoddemus review?

**Comment by dajose** [comment]
sorry, I made a mess with my branch and accidentally closed the pr for a bit :sweat:

**Comment by nicoddemus** [comment]
`1.3.0` released, thanks @dajose!

**Pull request merged**
