### PR TITLE
Log gtest/boost stdout/stderr when log-level is INFO

### LINKED ISSUE #41: Verbose boost test logging to stdout
Hi,

This is a very useful plugin!  There's only one thing I haven't been able to get working.

When I execute a Boost Test from the command line I like to see the output of each check, by passing the following parameters

`./my_test -l all`

You get output like:

`my_test.cpp(20): info: check val->getStringValue() == test_string has passed`

Or perhaps more importantly output from BOOST_WARN is completely swallowed, eg:

`./my_test.cpp(15): warning: in "MyBoostTests": condition sp.foo() == "Bar" is not satisfied ["Blah" != "Bar"]`

I assumed I'd be able to get this in pytest using something like:

`pytest -v -ra -o cpp_arguments='-l all'`

But the output is still at the unit test level not the BOOST_TEST level:

`my_test::my_test PASSED` 

How can I increase the output to the terminal?

Thanks!

### PR DESCRIPTION
**Pull request by dajose**
closes #41

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @dajose, thanks for the PR!

I'm not sure I'm a fan of hijacking logging.info like that: `pytest-cpp` is often used to run other kinds of tests (like normal python tests) alongside C++ tests. 

How about the original idea, of just printing the output of the underlying executable to stdout? That's how other plugins do this, notably `pytester`.

**Comment by The-Compiler** [comment]
FWIW I don't actively use this plugin, but I'd probably vote for a separate report section, similar to what e.g. pytest-qt does.

**Comment by dajose** [comment]
I see your point, but wouldn't it be more natural to use it on logs? Even if running alongside other tests, when I wanna see more data of the test I increase the log verbosity.

Now I agree INFO level could be extra noisy for this purpose :thinking: but maybe DEBUG

**Comment by dajose** [comment]
@nicoddemus I think I'll close this PR and do the cpp-verbose flag idea. Can you help me with #50 ? I think I'd have to touch lines of code the other does and I'd like to avoid conflicts

**Comment by nicoddemus** [comment]
> but I'd probably vote for a separate report section, similar to what e.g. pytest-qt does.

Oh I agree, it didn't occur to me but that's a better idea and fits better to how things work overall.

> Can you help me with #50 ?

Yeah, I've been meaning to but haven't had the time yet. But it is definitely on my TODO list, hopefully I will have some free time tomorrow to get to it.

**Comment by dajose** [comment]
wait, I got lost with @The-Compiler comment, I thought he was talking about the cpp-verbose flag.. how is that about a _separate report section_ ?

**Comment by nicoddemus** [comment]
@The-Compiler is mentioning [Item.add_report_section](https://docs.pytest.org/en/stable/reference.html?highlight=add_report_section#pytest.nodes.Item.add_report_section). This will be displayed automatically by pytest if a test fails.

We could add the full test output like this: `item.add_report_section("call", "c++", output)`.

**Comment by dajose** [comment]
:thinking: but that wouldnt solve #41 as the output would be shown only in case of error 

(let me post this dicussion back to #41, I created a mess initiating a discussion here :sweat_smile: )

**Pull request closed without merging**
